const AssetsFields: FormField[] = [
  {
    placeholder: 'Id',
    type: 'text',
    name: 'ID',
    label: 'ID',
    widthInDesktop: 'half',
  },
  {
    placeholder: 'Author',
    type: 'text',
    name: 'Author',
    label: 'Author',
    widthInDesktop: 'half',
  },
  {
    placeholder: 'Asset Status',
    type: 'text',
    name: 'Asset Status',
    label: 'Asset Status',
    widthInDesktop: 'half',
  },
  {
    placeholder: 'Location Status',
    type: 'text',
    name: 'Location Status',
    label: 'Location Status',
    widthInDesktop: 'half',
  },
  {
    label: 'Add date',
    type: 'text',
    name: 'Add date',
    widthInDesktop: 'half',
    placeholder: '12/12/2020',
  },
  {
    label: 'Model Date',
    type: 'text',
    name: 'Model Date',
    widthInDesktop: 'half',
    placeholder: '12/12/2020',
  },
  {
    placeholder: 'Serial Number',
    type: 'text',
    name: 'Serial Number',
    label: 'Serial Number',
    widthInDesktop: 'half',
  },
  {
    placeholder: 'Action Logistics ID',
    type: 'text',
    name: 'Action Logistics ID',
    label: 'Action Logistics ID',
    widthInDesktop: 'half',
  },
  {
    placeholder: 'CAPEX/OPEX',
    type: 'text',
    name: 'CAPEX/OPEX',
    label: 'CAPEX/OPEX',
    widthInDesktop: 'half',
  },
  {
    placeholder: 'CAPEX',
    type: 'text',
    name: 'CAPEX',
    label: 'CAPEX',
    widthInDesktop: 'half',
  },
  {
    placeholder: 'Model',
    type: 'text',
    name: 'Model',
    label: 'Model',
    widthInDesktop: 'half',
  },
  {
    placeholder: 'Asset',
    type: 'text',
    name: 'Asset',
    label: 'Asset',
    widthInDesktop: 'half',
  },
  {
    label: 'Manufacturer',
    type: 'select',
    name: 'Manufacturer',
    widthInDesktop: 'half',
    placeholder: 'Manufacturer',
    optionsSelect: ['Manufacturer 1', 'Manufacturer 2', 'Manufacturer 3'],
  },
  {
    label: 'Asset Type',
    type: 'select',
    name: 'Asset Type',
    widthInDesktop: 'half',
    placeholder: 'Asset Type',
    optionsSelect: ['Asset Type 1', 'Asset Type 2', 'Asset Type 3'],
  },
  {
    label: 'Asset Subtype',
    type: 'select',
    name: 'Asset Subtype',
    widthInDesktop: 'half',
    placeholder: 'Asset Subtype',
    optionsSelect: ['Asset Subtype 1', 'Asset Subtype 2', 'Asset Subtype 3'],
  },
  {
    label: 'Location',
    type: 'select',
    name: 'Location',
    widthInDesktop: 'half',
    placeholder: 'Location',
    optionsSelect: ['Location 1', 'Location 2', 'Location 3'],
  },
  {
    label: 'Asset Owner',
    type: 'select',
    name: 'Asset Owner',
    widthInDesktop: 'half',
    placeholder: 'Asset Owner',
    optionsSelect: ['Asset Owner 1', 'Asset Owner 2', 'Asset Owner 3'],
  },
  {
    label: 'Section',
    type: 'select',
    name: 'Section',
    widthInDesktop: 'half',
    placeholder: 'Section',
    optionsSelect: ['Section 1', 'Section 2', 'Section 3'],
  },
  {
    label: 'Parent Asset',
    type: 'select',
    name: 'Parent Asset',
    widthInDesktop: 'half',
    placeholder: 'Parent Asset',
    optionsSelect: ['Parent Asset 1', 'Parent Asset 2', 'Parent Asset 3'],
  },
  {
    label: 'Manufacture warranty',
    type: 'select',
    name: 'Manufacture warranty',
    widthInDesktop: 'half',
    placeholder: 'Manufacture warranty',
    optionsSelect: ['Manufacture warranty 1', 'Manufacture warranty 2', 'Manufacture warranty 3'],
  },
  {
    label: 'Buy date',
    type: 'text',
    name: 'Buy date',
    widthInDesktop: 'half',
    placeholder: '12/12/2020',
  },
  {
    placeholder: 'Insurence',
    type: 'text',
    name: 'Insurence',
    label: 'Insurence',
    widthInDesktop: 'half',
  },
  {
    placeholder: 'Insurence Type',
    type: 'select',
    name: 'Insurence Type',
    label: 'Insurence Type',
    widthInDesktop: 'half',
    optionsSelect: ['Insurence Type 1', 'Insurence Type 2', 'Insurence Type 3'],
  },
];

export { AssetsFields };
